# -*- coding: utf-8 -*-
"""Fakenewsdetection1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rTAfAahb7yjosq3Yfjh2H781hBhj1qhd
"""

!pip uninstall -y transformers peft tokenizers huggingface-hub -q
!pip install transformers==4.36.2 tokenizers==0.15.2 huggingface-hub==0.36.2 scikit-learn lime -q

!pip install accelerate==0.25.0 -q

import torch
print(torch.cuda.is_available())

import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

fake = pd.read_csv("/content/drive/MyDrive/machinetestAI/Fake.csv")
real = pd.read_csv("/content/drive/MyDrive/machinetestAI/True.csv")

fake["label"] = 0
real["label"] = 1

# 🔥 FIX 2: Balanced + controlled sampling
fake = fake.sample(2000, random_state=42)
real = real.sample(2000, random_state=42)

# 🔥 FIX 3: Proper shuffle
df = pd.concat([fake, real]).sample(frac=1, random_state=42).reset_index(drop=True)

df = df[["text", "label"]]

print(df["label"].value_counts())

train_texts, val_texts, train_labels, val_labels = train_test_split(
    df["text"], df["label"], test_size=0.2, random_state=42
)

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

train_encodings = tokenizer(
    list(train_texts),
    truncation=True,
    padding=True,
    max_length=128
)

val_encodings = tokenizer(
    list(val_texts),
    truncation=True,
    padding=True,
    max_length=128
)

class NewsDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = list(labels)

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = NewsDataset(train_encodings, train_labels)
val_dataset = NewsDataset(val_encodings, val_labels)

model = BertForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=2
)

def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, preds, average='binary'
    )
    acc = accuracy_score(labels, preds)

    return {
        "accuracy": acc,
        "f1": f1,
        "precision": precision,
        "recall": recall
    }

training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=2,
    per_device_train_batch_size=8,
    evaluation_strategy="epoch",
    logging_dir="./logs",
    save_strategy="epoch",
    load_best_model_at_end=True,

    # 🔥 ADD THIS
    weight_decay=0.01,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics
)

trainer.train()

model = trainer.model

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

trainer.evaluate()

model.save_pretrained("fake_news_model")
tokenizer.save_pretrained("fake_news_model")

import torch.nn.functional as F

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

def predict_news(text):
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=128
    )

    inputs = {key: val.to(device) for key, val in inputs.items()}

    model.eval()
    with torch.no_grad():
        outputs = model(**inputs)

    # 🔥 ADD THIS LINE (DEBUG)
    print("LOGITS:", outputs.logits)

    probs = F.softmax(outputs.logits, dim=1)

    fake_prob = probs[0][0].item()
    real_prob = probs[0][1].item()

    pred = torch.argmax(probs).item()
    confidence = probs[0][pred].item()

    label = "REAL" if pred == 1 else "FAKE"

    return label, confidence

print(predict_news("Government announces new policy for farmers"))
print(predict_news("Shocking cure discovered overnight!!!"))
print(predict_news("NASA confirms water found on Mars"))

print(predict_news("NASA confirms water on Mars"))

print(outputs.logits)

